CREATE OR REPLACE PACKAGE merge_row_count AS
  FUNCTION ins RETURN INTEGER;
  FUNCTION upd RETURN INTEGER;
  FUNCTION del RETURN INTEGER;

  FUNCTION get_inserted( sql_row_count INTEGER DEFAULT NULL ) RETURN INTEGER;
  FUNCTION get_updated( sql_row_count INTEGER DEFAULT NULL ) RETURN INTEGER;
  FUNCTION get_deleted( sql_row_count INTEGER DEFAULT NULL ) RETURN INTEGER;

END;
/
